apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-typescript-demo-deploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api-typescript-demo
        mode: canary
    spec:
      containers:
      - name: primary
        env:
        - name: env
          value: prod
        - name: LOG
          value: TRACE
        resources:
          limits:
            memory: 128Mi