---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-typescript-demo
  labels:
    app: api-typescript-demo
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: api-typescript-demo
  template:
    metadata:
      labels:
        app: api-typescript-demo
    spec:
      containers:
      - name: primary
        image: ${image}
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 100Mi
        readinessProbe:
          httpGet:
            path: /
            port: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
        envFrom:
        - configMapRef:
            name: api-typescript-demo-config
      imagePullSecrets:
      - name: regcred-harbor
---

kind: Service
apiVersion: v1
metadata:
  name: api-typescript-demo
  namespace: digital-dashboard  
spec:
  selector:
    app: api-typescript-demo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: api-typescript-demo
  namespace: digital-dashboard  
spec:
  rules:
  - host: $(ING_NAME).digital-dashboard.arctic.true.th
    http:
      paths:
      - backend:
          serviceName: api-typescript-demo
          servicePort: 80
