apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-typescript-deploy
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: primary
        env:
        - name: env
          value: staging
        resources:
          limits:
            memory: 128Mi